services:
  - type: web
    name: smart-city-analytics-platform
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt && cd frontend && npm install && npm run build
    startCommand: cd backend && python run.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: NODE_VERSION
        value: "18.20.0"
    disk:
      name: smartcity-db
      mountPath: /opt/render/project/src/backend
      sizeGB: 1
